version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: timelapse_frontend
    environment:
      - CAPTURE_INTERVAL=30  # Time interval in seconds (default 120)
      - OUTPUT_DIR=/usr/src/app/timelapse/frames  # Directory for storing captured frames
      - VIDEO_OUTPUT=/usr/src/app/timelapse/videos  # Path for the timelapse videos
      - FRAME_WIDTH=1280  # Width of the captured frames
      - FRAME_HEIGHT=720  # Height of the captured frames
      - FPS=30  # Frames per second for the timelapse video
    secrets:
      - rtsp_url
    ports:
      - "5000:5000"  # Expose the web UI on port 5000
    volumes:
      - ./timelapse:/usr/src/app/timelapse  # Bind mount the frame output folder
    restart: unless-stopped
    networks:
      - cam-timelapse-network    

  capture:
    build:
      context: .
      dockerfile: capture.Dockerfile
    container_name: timelapse_capture
    environment:
      - CAPTURE_INTERVAL=30  # Time interval in seconds (default 120)
      - OUTPUT_DIR=/usr/src/app/timelapse/frames  # Directory for storing captured frames
      - VIDEO_OUTPUT=/usr/src/app/timelapse/videos  # Path for the timelapse videos
      - FRAME_WIDTH=1280  # Width of the captured frames
      - FRAME_HEIGHT=720  # Height of the captured frames
      - FPS=30  # Frames per second for the timelapse video
    secrets:
      - rtsp_url
    volumes:
      - ./timelapse:/usr/src/app/timelapse  # Bind mount the frame output folder
    restart: unless-stopped
    networks:
      - cam-timelapse-network    

secrets:
  rtsp_url:
    file: .secrets

networks:
  cam-timelapse-network: